version: '3.8'

networks:
  neumachile:
    external: true

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver-neumatruck
    restart: unless-stopped
    ports:
      - "8003:8080"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - neumachile

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: neumatruck-backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - neumachile
